package json.execute.vm.entity.frame;

public enum FrameKind {

    FRAME_APPLY_TARGET,
    FRAME_BINARY_LEFT,
    FRAME_BINARY_RIGHT,
    FRAME_BUILTIN_FILTER,
    FRAME_BUILTIN_FORCE_THUNKS,
    FRAME_CALL,
    FRAME_ERROR,
    FRAME_EQUALITY_MANIFEST,
    FRAME_IF,
    FRAME_INDEX_TARGET,
    FRAME_INDEX_INDEX,
    FRAME_LOCAL,
    FRAME_OBJECT,
    FRAME_OBJECT_COMP_ARRAY,
    FRAME_OBJECT_COMP_ELEMENT,
    FRAME_STRING_CONCAT,
    FRAME_UNARY


}
